name: rabies_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python>=3.11
  
  # Core data analysis
  - pandas>=2.0.0
  - numpy>=1.24.0
  
  # Statistical analysis
  - scipy>=1.10.0
  - statsmodels>=0.14.0
  
  # Machine learning (for stratified analytics)
  - scikit-learn>=1.3.0
  
  # Plotting and visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  
  # Excel file handling
  - openpyxl>=3.1.0
  
  # Optional: For enhanced plotting
  - plotly>=5.0.0
  
  # Jupyter notebook support (optional)
  - jupyter
  - ipykernel
  
  # Development tools (optional)
  - black
  - flake8
  - pytest
